// Package genzod generates TypeScript Zod schemas from Go structs annotated
// with a //genzod comment. It is intentionally minimal: only standard-library
// go/ast is used, and the output is structural scaffolding that can be
// extended by hand-written business-level validation where needed.
package genzod

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Generate reads all .go files in dir, parses them, and writes generated Zod
// schemas for structs marked with //genzod to w.
func Generate(dir string, w io.Writer) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read dir %s: %w", dir, err)
	}

	fset := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		src, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		files = append(files, f)
	}

	return generateFromFiles(fset, files, w)
}

func generateFromFiles(fset *token.FileSet, files []*ast.File, w io.Writer) error {
	structs, err := collectStructs(fset, files)
	if err != nil {
		return err
	}

	ordered, err := topoSort(structs)
	if err != nil {
		return err
	}

	if _, err := fmt.Fprintln(w, "// Code generated by genzod. DO NOT EDIT."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, `import { z } from "zod";`); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}

	for _, name := range ordered {
		s := structs[name]
		if err := writeSchema(w, s); err != nil {
			return err
		}
	}
	return nil
}

// DomainRule maps a protocol source filename prefix to a schema domain.
type DomainRule struct {
	Prefix string
	Domain string
}

// BaseDomain receives structs whose source file matches no DomainRule prefix.
const BaseDomain = "base"

// DefaultDomainRules groups protocol source files into schema domains by
// filename prefix; the first matching rule wins.
var DefaultDomainRules = []DomainRule{
	{Prefix: "message_agent_", Domain: "agent"},
	{Prefix: "message_schedule", Domain: "schedule-loop"},
	{Prefix: "message_loop", Domain: "schedule-loop"},
	{Prefix: "message_tmux", Domain: "terminal"},
	{Prefix: "message_terminal", Domain: "terminal"},
	{Prefix: "terminal", Domain: "terminal"},
	{Prefix: "message_worktree", Domain: "workspace"},
	{Prefix: "message_editor", Domain: "workspace"},
}

// GenerateMulti writes one schema file per domain
// (protocol-schemas-<domain>.ts) plus a barrel (protocol-schemas.ts) that
// re-exports every domain, grouping structs by source filename prefix via
// DefaultDomainRules.
func GenerateMulti(dir, outDir string) error {
	return GenerateMultiWithRules(dir, outDir, DefaultDomainRules)
}

// GenerateMultiWithRules is GenerateMulti with a caller-supplied rule set.
func GenerateMultiWithRules(dir, outDir string, rules []DomainRule) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read dir %s: %w", dir, err)
	}

	fset := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		src, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		files = append(files, f)
	}

	structs, err := collectStructs(fset, files)
	if err != nil {
		return err
	}
	ordered, err := topoSort(structs)
	if err != nil {
		return err
	}

	domainOf := make(map[string]string, len(structs))
	for name, s := range structs {
		domainOf[name] = domainForFile(rules, s.File)
	}

	// Group struct names per domain while preserving the topological order so
	// intra-domain references are always defined before use.
	byDomain := make(map[string][]string)
	for _, name := range ordered {
		d := domainOf[name]
		byDomain[d] = append(byDomain[d], name)
	}

	domains := make([]string, 0, len(byDomain))
	for d := range byDomain {
		domains = append(domains, d)
	}
	sort.Strings(domains)

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	for _, domain := range domains {
		if err := writeDomainFile(outDir, domain, byDomain[domain], structs, domainOf); err != nil {
			return err
		}
	}
	return writeBarrelFile(outDir, domains)
}

func domainForFile(rules []DomainRule, file string) string {
	for _, r := range rules {
		if strings.HasPrefix(file, r.Prefix) {
			return r.Domain
		}
	}
	return BaseDomain
}

func domainFileName(domain string) string {
	return fmt.Sprintf("protocol-schemas-%s.ts", domain)
}

// domainImportPath returns the ESM import specifier for a domain file.
func domainImportPath(domain string) string {
	return "./" + strings.TrimSuffix(domainFileName(domain), ".ts") + ".js"
}

func writeDomainFile(outDir, domain string, names []string, structs map[string]*structDef, domainOf map[string]string) error {
	importsByDomain := make(map[string]map[string]struct{})
	for _, name := range names {
		for dep := range structs[name].Deps {
			depDomain := domainOf[dep]
			if depDomain == domain {
				continue
			}
			if importsByDomain[depDomain] == nil {
				importsByDomain[depDomain] = make(map[string]struct{})
			}
			importsByDomain[depDomain][dep+"Schema"] = struct{}{}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genzod. DO NOT EDIT.\n\n")
	buf.WriteString("import { z } from \"zod\";\n")

	importDomains := make([]string, 0, len(importsByDomain))
	for d := range importsByDomain {
		importDomains = append(importDomains, d)
	}
	sort.Strings(importDomains)
	for _, d := range importDomains {
		refNames := make([]string, 0, len(importsByDomain[d]))
		for ref := range importsByDomain[d] {
			refNames = append(refNames, ref)
		}
		sort.Strings(refNames)
		fmt.Fprintf(&buf, "import { %s } from \"%s\";\n", strings.Join(refNames, ", "), domainImportPath(d))
	}
	buf.WriteString("\n")

	for _, name := range names {
		if err := writeSchema(&buf, structs[name]); err != nil {
			return err
		}
	}

	path := filepath.Join(outDir, domainFileName(domain))
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeBarrelFile(outDir string, domains []string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by genzod. DO NOT EDIT.\n\n")
	for _, d := range domains {
		fmt.Fprintf(&buf, "export * from \"%s\";\n", domainImportPath(d))
	}
	path := filepath.Join(outDir, "protocol-schemas.ts")
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

type structDef struct {
	Name   string
	File   string
	Fields []fieldDef
	Deps   map[string]struct{}
}

type fieldDef struct {
	JSONName string
	Schema   string
}

func collectStructs(fset *token.FileSet, files []*ast.File) (map[string]*structDef, error) {
	// First pass: collect all marked struct names so that field resolution can
	// reference structs defined later in the source.
	marked := make(map[string]*ast.StructType)
	markedFile := make(map[string]string)
	for _, f := range files {
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !hasGenZodComment(genDecl.Doc, ts.Doc) {
					continue
				}
				marked[ts.Name.Name] = st
				markedFile[ts.Name.Name] = filepath.Base(fset.Position(ts.Pos()).Filename)
			}
		}
	}

	// Second pass: build definitions with full knowledge of marked structs.
	structs := make(map[string]*structDef)
	for name, st := range marked {
		def := &structDef{Name: name, File: markedFile[name], Deps: make(map[string]struct{})}
		for _, field := range st.Fields.List {
			fds, err := buildFields(field, marked, def.Deps)
			if err != nil {
				return nil, fmt.Errorf("struct %s field %s: %w", name, fieldNames(field), err)
			}
			def.Fields = append(def.Fields, fds...)
		}
		structs[name] = def
	}
	return structs, nil
}

func hasGenZodComment(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc == nil {
			continue
		}
		for _, c := range doc.List {
			if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "genzod" {
				return true
			}
		}
	}
	return false
}

func fieldNames(field *ast.Field) string {
	if len(field.Names) == 0 {
		return "<embedded>"
	}
	var names []string
	for _, n := range field.Names {
		names = append(names, n.Name)
	}
	return strings.Join(names, ", ")
}

func buildFields(field *ast.Field, marked map[string]*ast.StructType, deps map[string]struct{}) ([]fieldDef, error) {
	if len(field.Names) == 0 {
		// Embedded fields are not supported in the MVP.
		return nil, nil
	}

	tag := reflectJSONTag(field.Tag)
	if tag.ignore {
		return nil, nil
	}

	schema, err := typeToSchema(field.Type, tag.omitempty, marked, deps)
	if err != nil {
		return nil, err
	}

	var fields []fieldDef
	for _, name := range field.Names {
		jsonName := tag.name
		if jsonName == "" {
			jsonName = lowerFirst(name.Name)
		}
		fields = append(fields, fieldDef{JSONName: jsonName, Schema: schema})
	}
	return fields, nil
}

type jsonTag struct {
	name      string
	omitempty bool
	ignore    bool
}

func reflectJSONTag(tag *ast.BasicLit) jsonTag {
	if tag == nil {
		return jsonTag{}
	}
	value := strings.Trim(tag.Value, "`")
	const prefix = "json:\""
	idx := strings.Index(value, prefix)
	if idx == -1 {
		return jsonTag{}
	}
	start := idx + len(prefix)
	end := strings.IndexByte(value[start:], '"')
	if end == -1 {
		return jsonTag{}
	}
	parts := strings.Split(value[start:start+end], ",")
	if parts[0] == "-" {
		return jsonTag{ignore: true}
	}
	result := jsonTag{name: parts[0]}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			result.omitempty = true
		}
	}
	return result
}

func typeToSchema(expr ast.Expr, omitempty bool, marked map[string]*ast.StructType, deps map[string]struct{}) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		schema, ok := primitiveSchema(t.Name)
		if !ok {
			if _, known := marked[t.Name]; known {
				deps[t.Name] = struct{}{}
				return schemaRef(t.Name+"Schema", omitempty), nil
			}
			return "", fmt.Errorf("unsupported primitive type: %s", t.Name)
		}
		return schemaRef(schema, omitempty), nil
	case *ast.StarExpr:
		inner, err := typeToSchema(t.X, false, marked, deps)
		if err != nil {
			return "", err
		}
		if omitempty {
			return inner + ".nullable().optional()", nil
		}
		return inner + ".nullable()", nil
	case *ast.ArrayType:
		el, err := typeToSchema(t.Elt, false, marked, deps)
		if err != nil {
			return "", err
		}
		return schemaRef("z.array("+el+")", omitempty), nil
	case *ast.MapType:
		keyIdent, ok := t.Key.(*ast.Ident)
		if !ok || keyIdent.Name != "string" {
			return "", fmt.Errorf("only map[string]T is supported")
		}
		val, err := typeToSchema(t.Value, false, marked, deps)
		if err != nil {
			return "", err
		}
		return schemaRef("z.record(z.string(), "+val+")", omitempty), nil
	case *ast.InterfaceType:
		if len(t.Methods.List) != 0 {
			return "", fmt.Errorf("non-empty interfaces are not supported")
		}
		return schemaRef("z.unknown()", omitempty), nil
	case *ast.SelectorExpr:
		// External types (e.g. json.RawMessage) fall back to unknown.
		return schemaRef("z.unknown()", omitempty), nil
	default:
		return "", fmt.Errorf("unsupported type expression: %T", expr)
	}
}

func primitiveSchema(name string) (string, bool) {
	switch name {
	case "string":
		return "z.string()", true
	case "bool":
		return "z.boolean()", true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "z.number()", true
	default:
		return "", false
	}
}

func schemaRef(schema string, omitempty bool) string {
	if omitempty {
		return schema + ".optional()"
	}
	return schema
}

func topoSort(structs map[string]*structDef) ([]string, error) {
	var order []string
	visited := make(map[string]bool)
	visiting := make(map[string]bool)

	var visit func(name string) error
	visit = func(name string) error {
		if visiting[name] {
			return fmt.Errorf("cycle detected involving %s", name)
		}
		if visited[name] {
			return nil
		}
		visiting[name] = true
		for dep := range structs[name].Deps {
			if _, ok := structs[dep]; !ok {
				return fmt.Errorf("struct %s depends on unknown type %s", name, dep)
			}
			if err := visit(dep); err != nil {
				return err
			}
		}
		visiting[name] = false
		visited[name] = true
		order = append(order, name)
		return nil
	}

	names := make([]string, 0, len(structs))
	for name := range structs {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		if err := visit(name); err != nil {
			return nil, err
		}
	}
	return order, nil
}

func writeSchema(w io.Writer, s *structDef) error {
	if _, err := fmt.Fprintf(w, "export const %sSchema = z.object({\n", s.Name); err != nil {
		return err
	}
	for _, f := range s.Fields {
		if _, err := fmt.Fprintf(w, "  %s: %s,\n", f.JSONName, f.Schema); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, "});"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "export type %s = z.infer<typeof %sSchema>;\n", s.Name, s.Name); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	return nil
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = rune(strings.ToLower(string(r[0]))[0])
	return string(r)
}
