package genzod

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTempFiles(t *testing.T, files map[string]string) string {
	t.Helper()
	dir, err := os.MkdirTemp("", "genzod-test-*")
	if err != nil {
		t.Fatalf("mkdir temp: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(dir) })
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return dir
}

func TestGenerate_BasicTypes(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"basic.go": `package protocol

//genzod
type Basic struct {
	Name    string  ` + "`json:\"name\"`" + `
	Count   int     ` + "`json:\"count\"`" + `
	Score   float64 ` + "`json:\"score\"`" + `
	Enabled bool    ` + "`json:\"enabled\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "export const BasicSchema = z.object({") {
		t.Errorf("missing BasicSchema declaration:\n%s", out)
	}
	wantParts := []string{
		"name: z.string()",
		"count: z.number()",
		"score: z.number()",
		"enabled: z.boolean()",
		"export type Basic = z.infer<typeof BasicSchema>;",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_OptionalAndNullable(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"optional.go": `package protocol

//genzod
type OptionalDemo struct {
	Required  string  ` + "`json:\"required\"`" + `
	Omitted   *string ` + "`json:\"omitted,omitempty\"`" + `
	Nullable  *string ` + "`json:\"nullable\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"required: z.string()",
		"omitted: z.string().nullable().optional()",
		"nullable: z.string().nullable()",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_CollectionsAndMaps(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"collections.go": `package protocol

//genzod
type Collections struct {
	Tags    []string          ` + "`json:\"tags\"`" + `
	Meta    map[string]string ` + "`json:\"meta\"`" + `
	Raw     map[string]interface{} ` + "`json:\"raw,omitempty\"`" + `
	Generic interface{}       ` + "`json:\"generic,omitempty\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"tags: z.array(z.string())",
		"meta: z.record(z.string(), z.string())",
		"raw: z.record(z.string(), z.unknown()).optional()",
		"generic: z.unknown().optional()",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_NestedStruct(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"nested.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type Outer struct {
	Inner  Inner   ` + "`json:\"inner\"`" + `
	Inners []Inner ` + "`json:\"inners,omitempty\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "export const InnerSchema = z.object({") {
		t.Errorf("missing InnerSchema:\n%s", out)
	}
	if !strings.Contains(out, "export const OuterSchema = z.object({") {
		t.Errorf("missing OuterSchema:\n%s", out)
	}
	if !strings.Contains(out, "inner: InnerSchema") {
		t.Errorf("missing nested inner reference:\n%s", out)
	}
	if !strings.Contains(out, "inners: z.array(InnerSchema).optional()") {
		t.Errorf("missing nested array reference:\n%s", out)
	}
}

func TestGenerate_IgnoresUnmarkedStructs(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"mixed.go": `package protocol

type Ignored struct {
	ID string ` + "`json:\"id\"`" + `
}

//genzod
type Included struct {
	ID string ` + "`json:\"id\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	if strings.Contains(out, "IgnoredSchema") {
		t.Errorf("IgnoredSchema should not be generated:\n%s", out)
	}
	if !strings.Contains(out, "IncludedSchema") {
		t.Errorf("IncludedSchema should be generated:\n%s", out)
	}
}

func TestGenerate_Header(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"basic.go": `package protocol

//genzod
type Basic struct {
	ID string ` + "`json:\"id\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	if !strings.HasPrefix(out, "// Code generated by genzod. DO NOT EDIT.") {
		t.Errorf("missing generated header:\n%s", out)
	}
	if !strings.Contains(out, `import { z } from "zod";`) {
		t.Errorf("missing zod import:\n%s", out)
	}
}

func TestGenerate_PointerEdgeCases(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"ptrs.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type PtrDemo struct {
	IntPtr    *int              ` + "`json:\"intPtr\"`" + `
	FloatPtr  *float64          ` + "`json:\"floatPtr\"`" + `
	BoolPtr   *bool             ` + "`json:\"boolPtr\"`" + `
	StructPtr *Inner            ` + "`json:\"structPtr\"`" + `
	SlicePtr  *[]string         ` + "`json:\"slicePtr\"`" + `
	MapPtr    *map[string]string ` + "`json:\"mapPtr\"`" + `
	NoTag     *string
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"intPtr: z.number().nullable()",
		"floatPtr: z.number().nullable()",
		"boolPtr: z.boolean().nullable()",
		"structPtr: InnerSchema.nullable()",
		"slicePtr: z.array(z.string()).nullable()",
		"mapPtr: z.record(z.string(), z.string()).nullable()",
		"noTag: z.string().nullable()",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_OmitemptyEdgeCases(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"omitempty.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type OmitemptyDemo struct {
	WithOmitempty     string  ` + "`json:\"withOmitempty,omitempty\"`" + `
	WithoutOmitempty  string  ` + "`json:\"withoutOmitempty\"`" + `
	PtrOmitempty      *int    ` + "`json:\"ptrOmitempty,omitempty\"`" + `
	PtrStructOmitempty *Inner ` + "`json:\"ptrStructOmitempty,omitempty\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"withOmitempty: z.string().optional()",
		"withoutOmitempty: z.string()",
		"ptrOmitempty: z.number().nullable().optional()",
		"ptrStructOmitempty: InnerSchema.nullable().optional()",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
	// withoutOmitempty must NOT have .optional()
	if strings.Contains(out, "withoutOmitempty: z.string().optional()") {
		t.Errorf("withoutOmitempty should not be optional:\n%s", out)
	}
}

func TestGenerate_ArrayEdgeCases(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"arrays.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type ArrayDemo struct {
	TwoD        [][]Inner   ` + "`json:\"twoD\"`" + `
	PtrElems    []*string   ` + "`json:\"ptrElems\"`" + `
	IfaceSlice  []interface{} ` + "`json:\"ifaceSlice\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"twoD: z.array(z.array(InnerSchema))",
		"ptrElems: z.array(z.string().nullable())",
		"ifaceSlice: z.array(z.unknown())",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_MapEdgeCases(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"maps.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type MapDemo struct {
	StructVals map[string]Inner    ` + "`json:\"structVals\"`" + `
	PtrVals    map[string]*string  ` + "`json:\"ptrVals\"`" + `
	SliceVals  map[string][]string ` + "`json:\"sliceVals\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"structVals: z.record(z.string(), InnerSchema)",
		"ptrVals: z.record(z.string(), z.string().nullable())",
		"sliceVals: z.record(z.string(), z.array(z.string()))",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
}

func TestGenerate_NonStringMapKeyErrors(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"badmap.go": `package protocol

//genzod
type BadMap struct {
	Data map[int]string ` + "`json:\"data\"`" + `
}
`,
	})

	var buf bytes.Buffer
	err := Generate(dir, &buf)
	if err == nil {
		t.Fatal("expected error for non-string map key, got nil")
	}
	if !strings.Contains(err.Error(), "only map[string]T is supported") {
		t.Errorf("expected error about map key type, got: %v", err)
	}
}

func TestGenerate_CombinedEdgeCases(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"kitchen.go": `package protocol

//genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}

//genzod
type KitchenSink struct {
	Name        string            ` + "`json:\"name\"`" + `
	Tag         string            ` + "`json:\"tag,omitempty\"`" + `
	Count       *int              ` + "`json:\"count\"`" + `
	PtrOmitempty *string          ` + "`json:\"ptrOmitempty,omitempty\"`" + `
	Items       []Inner           ` + "`json:\"items\"`" + `
	Meta        map[string]string ` + "`json:\"meta\"`" + `
	Raw         interface{}       ` + "`json:\"raw,omitempty\"`" + `
	Ignored     string            ` + "`json:\"-\"`" + `
	CustomName  string            ` + "`json:\"custom_name\"`" + `
}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	wantParts := []string{
		"name: z.string()",
		"tag: z.string().optional()",
		"count: z.number().nullable()",
		"ptrOmitempty: z.string().nullable().optional()",
		"items: z.array(InnerSchema)",
		"meta: z.record(z.string(), z.string())",
		"raw: z.unknown().optional()",
		"custom_name: z.string()",
	}
	for _, part := range wantParts {
		if !strings.Contains(out, part) {
			t.Errorf("expected output to contain %q:\n%s", part, out)
		}
	}
	if strings.Contains(out, "ignored") {
		t.Errorf("json:\"-\" field should be excluded from output:\n%s", out)
	}
}

func TestGenerateMulti_DomainGroupingAndCrossDomainImports(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"message_common.go": `package protocol

// genzod
type Base struct {
	Value int ` + "`json:\"value\"`" + `
}
`,
		"message_agent_inbound.go": `package protocol

// genzod
type AgentThing struct {
	Name  string ` + "`json:\"name\"`" + `
	Base  Base   ` + "`json:\"base\"`" + `
}
`,
		"terminal.go": `package protocol

// genzod
type TermCell struct {
	Char string ` + "`json:\"char\"`" + `
}
`,
	})

	outDir := t.TempDir()
	if err := GenerateMulti(dir, outDir); err != nil {
		t.Fatalf("GenerateMulti failed: %v", err)
	}

	read := func(name string) string {
		t.Helper()
		data, err := os.ReadFile(filepath.Join(outDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		return string(data)
	}

	base := read("protocol-schemas-base.ts")
	if !strings.Contains(base, "export const BaseSchema = z.object({") {
		t.Errorf("base domain file missing BaseSchema:\n%s", base)
	}
	if strings.Contains(base, "import {") && !strings.Contains(base, `from "zod"`) {
		t.Errorf("base domain file should have no cross-domain imports:\n%s", base)
	}

	agent := read("protocol-schemas-agent.ts")
	if !strings.Contains(agent, `import { BaseSchema } from "./protocol-schemas-base.js";`) {
		t.Errorf("agent domain file missing cross-domain import:\n%s", agent)
	}
	if !strings.Contains(agent, "base: BaseSchema") {
		t.Errorf("agent domain file missing BaseSchema reference:\n%s", agent)
	}

	terminal := read("protocol-schemas-terminal.ts")
	if !strings.Contains(terminal, "export const TermCellSchema = z.object({") {
		t.Errorf("terminal domain file missing TermCellSchema:\n%s", terminal)
	}

	barrel := read("protocol-schemas.ts")
	for _, want := range []string{
		`export * from "./protocol-schemas-agent.js";`,
		`export * from "./protocol-schemas-base.js";`,
		`export * from "./protocol-schemas-terminal.js";`,
	} {
		if !strings.Contains(barrel, want) {
			t.Errorf("barrel missing %q:\n%s", want, barrel)
		}
	}
}

func TestGenerateMulti_UnmatchedFilesFallBackToBaseDomain(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"unmatched_prefix.go": `package protocol

// genzod
type Odd struct {
	ID string ` + "`json:\"id\"`" + `
}
`,
	})

	outDir := t.TempDir()
	if err := GenerateMulti(dir, outDir); err != nil {
		t.Fatalf("GenerateMulti failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "protocol-schemas-base.ts"))
	if err != nil {
		t.Fatalf("expected base domain file: %v", err)
	}
	if !strings.Contains(string(data), "export const OddSchema = z.object({") {
		t.Errorf("base domain file missing OddSchema:\n%s", data)
	}

	barrel, err := os.ReadFile(filepath.Join(outDir, "protocol-schemas.ts"))
	if err != nil {
		t.Fatalf("expected barrel file: %v", err)
	}
	if !strings.Contains(string(barrel), `export * from "./protocol-schemas-base.js";`) {
		t.Errorf("barrel missing base re-export:\n%s", barrel)
	}
}

func TestGenerateMulti_PreservesTopologicalOrderWithinDomain(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"message_common.go": `package protocol

// genzod
type Outer struct {
	Inner Inner ` + "`json:\"inner\"`" + `
}

// genzod
type Inner struct {
	Value int ` + "`json:\"value\"`" + `
}
`,
	})

	outDir := t.TempDir()
	if err := GenerateMulti(dir, outDir); err != nil {
		t.Fatalf("GenerateMulti failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "protocol-schemas-base.ts"))
	if err != nil {
		t.Fatalf("read base domain file: %v", err)
	}
	out := string(data)
	innerIdx := strings.Index(out, "export const InnerSchema")
	outerIdx := strings.Index(out, "export const OuterSchema")
	if innerIdx == -1 || outerIdx == -1 {
		t.Fatalf("missing schema declarations:\n%s", out)
	}
	if innerIdx > outerIdx {
		t.Errorf("InnerSchema must be defined before OuterSchema:\n%s", out)
	}
}

func TestGenerate_EmptyStruct(t *testing.T) {
	dir := writeTempFiles(t, map[string]string{
		"empty.go": `package protocol

//genzod
type Empty struct {}
`,
	})

	var buf bytes.Buffer
	if err := Generate(dir, &buf); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "export const EmptySchema = z.object({") {
		t.Errorf("missing EmptySchema declaration:\n%s", out)
	}
	if !strings.Contains(out, "});") {
		t.Errorf("missing closing brace:\n%s", out)
	}
}
